#!/usr/bin/env python3
"""Fetch news from Perplexity API and save to categorized markdown files."""

import os
import json
import requests
from datetime import datetime
from pathlib import Path

# News categories to track
CATEGORIES = {
    "technology": "Latest technology news and innovations",
    "business": "Business and economy news updates",
    "sports": "Sports news and highlights",
    "entertainment": "Entertainment and celebrity news",
    "science": "Science discoveries and research",
    "health": "Health and medical news",
    "world": "World news and international events",
    "india": "Latest news from India"
}

API_KEY = os.getenv("PERPLEXITY_API_KEY")
API_URL = "https://api.perplexity.ai/chat/completions"

def fetch_category_news(category, description):
    """Fetch news for a specific category using Perplexity API."""
    
    # Check if API key exists
    if not API_KEY:
        print("⚠️  PERPLEXITY_API_KEY not set. Using demo mode.")
        return generate_demo_content(category, "API key not found in environment")
    
    print(f"   API Key found: {API_KEY[:10]}...{API_KEY[-4:]}")
    
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": "sonar",  # Changed from llama-3.1-sonar-small-128k-online to sonar
        "messages": [
            {
                "role": "system",
                "content": "You are a news aggregator. Provide concise, factual news summaries with sources."
            },
            {
                "role": "user",
                "content": f"Give me the top 5 latest {description} from today. Format each as: **Title** - Brief summary (1-2 sentences)."
            }
        ],
        "max_tokens": 1000,
        "temperature": 0.2
    }
    
    try:
        print(f"   Making API request to {API_URL}...")
        response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
        
        # Log response status
        print(f"   Response status: {response.status_code}")
        
        if response.status_code != 200:
            print(f"   Response body: {response.text[:500]}")
            return generate_demo_content(category, f"API error {response.status_code}: {response.text[:200]}")
        
        response.raise_for_status()
        data = response.json()
        content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
        
        if content:
            print(f"   ✅ Got {len(content)} characters of content")
            return content
        else:
            print(f"   ⚠️  Empty response from API")
            return generate_demo_content(category, "API returned empty content")
            
    except requests.exceptions.RequestException as e:
        print(f"   ❌ Network error: {e}")
        return generate_demo_content(category, f"Network error: {str(e)}")
    except Exception as e:
        print(f"   ❌ Unexpected error: {e}")
        return generate_demo_content(category, f"Error: {str(e)}")

def generate_demo_content(category, reason="Unknown"):
    """Generate demo content when API key is not available."""
    return f"""**Demo Mode Active**

This is placeholder content for {category.upper()} category.

**Reason:** {reason}

To get real news:
1. Get Perplexity API key from https://www.perplexity.ai/settings/api
2. Add it as GitHub Secret: PERPLEXITY_API_KEY
3. Re-run the workflow

*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M IST')}*
"""

def save_news(category, content):
    """Save news content to markdown file."""
    
    # Create directory structure: news/YYYY-MM-DD/category.md
    today = datetime.now().strftime("%Y-%m-%d")
    news_dir = Path("news") / today
    news_dir.mkdir(parents=True, exist_ok=True)
    
    filepath = news_dir / f"{category}.md"
    
    # Create markdown content
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M IST")
    markdown = f"""# {category.upper()} News

**Last Updated:** {timestamp}

---

{content}

---

*Auto-generated by [Perplexity News Tracker](https://github.com/myidkd1-coder/perplexity-news-tracker)*
"""
    
    filepath.write_text(markdown, encoding="utf-8")
    print(f"✅ Saved: {filepath}")

def main():
    """Main function to fetch and save news for all categories."""
    print("🚀 Starting news fetch...\n")
    print(f"Environment check:")
    print(f"  - API_KEY present: {bool(API_KEY)}")
    if API_KEY:
        print(f"  - API_KEY length: {len(API_KEY)}")
        print(f"  - API_KEY preview: {API_KEY[:10]}...{API_KEY[-4:]}\n")
    else:
        print(f"  - No API key found in environment!\n")
    
    for category, description in CATEGORIES.items():
        print(f"📰 Fetching {category}...")
        content = fetch_category_news(category, description)
        save_news(category, content)
        print()
    
    print("✨ News fetch complete!")

if __name__ == "__main__":
    main()
